# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/polina/Desktop/Practice/LAB_1/CMakeLists.txt))

/Users/polina/Desktop/Practice/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/local/bin/cmake -H/Users/polina/Desktop/Practice -B/Users/polina/Desktop/Practice
